name: Preview

concurrency: ${{matrix.environment}}

on:
  pull_request:
  workflow_dispatch:

env:
  # Disable the .NET logo in the console output.
  DOTNET_NOLOGO: true
  # Disable the .NET first time experience to skip caching NuGet packages and speed up the build.
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  # Disable sending .NET CLI telemetry to Microsoft.
  DOTNET_CLI_TELEMETRY_OPTOUT: true

jobs:
  preview:
    name: Preview-${{matrix.environment}}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment:
          - development
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4.2.2
      - name: "Install .NET SDK"
        uses: actions/setup-dotnet@v3.0.3
      - name: "Dotnet Tool Restore"
        run: dotnet tool restore
        shell: pwsh
      - name: "Dotnet Cake Build"
        run: dotnet cake --target=Build
        shell: pwsh
      - name: "Dotnet Cake Test"
        run: dotnet cake --target=Test
        shell: pwsh
      - name: "Pulumi Preview"
        uses: pulumi/actions@v3.20.0
        with:
          command: preview
          stack-name: ${{matrix.environment}}
          work-dir: Source/Ummati.Infrastructure
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
      - name: "Publish Artefacts"
        uses: actions/upload-artifact@v3.1.3
        with:
          name: Artefacts
          path: "./Artefacts"
